# Logistic Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('credit.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[ 1.93193782e+00 -4.10159984e-01 -3.40815266e-01 ...  4.19313800e-02
  -3.77721190e-02  9.99000000e+00]
 [ 1.48623788e+00 -2.90469971e-01 -2.00693672e+00 ... -3.06144480e-02
   3.47226350e-02  2.67600000e+02]
 [-1.71231152e+00  2.10587424e-01 -9.71219080e-02 ...  1.47251780e-01
   1.46512010e-02  4.49000000e+00]
 ...
 [-6.76142671e-01  1.12636606e+00 -2.21369952e+00 ...  3.85107449e-01
   1.94361479e-01  7.78900000e+01]
 [-3.11383161e+00  5.85864172e-01 -5.39973021e+00 ...  8.84875540e-01
  -2.53700319e-01  2.45000000e+02]
 [ 1.99197610e+00  1.58475887e-01 -2.58344065e+00 ...  2.98758200e-03
  -1.53088130e-02  4.25300000e+01]]


In [4]:
print(y)

[0 0 0 ... 1 1 1]


## Splitting the dataset into the Training set and Test set

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [6]:
print(X_train)

[[-3.21895201e+00  2.70853541e+00 -3.26304159e+00 ... -3.10518998e-01
  -7.45294627e-01  6.06000000e+01]
 [-8.46934266e-01  4.54591740e-02  2.16062009e+00 ...  3.04011100e-01
   1.66450783e-01  1.19900000e+01]
 [-3.63174981e+00  3.16334707e+00  1.93532124e-01 ... -8.77502000e-03
   3.85572770e-02  1.54000000e+00]
 ...
 [-1.10847822e+00  3.44895257e+00 -6.21697181e+00 ...  2.29327220e-01
   2.08829892e-01  1.80000000e+01]
 [-1.81328048e+00  4.91785071e+00 -5.92612969e+00 ...  8.94766672e-01
   5.69518600e-01  1.00000000e+00]
 [-4.56634157e+00  3.35345148e+00 -4.57202781e+00 ...  1.95985146e-01
   1.41115103e-01  1.00000000e+00]]


In [7]:
print(y_train)

[1 0 0 1 1 1 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0
 1 1 0 1 0 1 1 1 0 0 0 0 1 1 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0
 0 0 0 1 0 1 1 1 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 1 0 1 0 1 1 1 1 1 1 0 1 0 0
 0 1 0 0 1 1 1 0 1 1 1 0 0 0 0 1 0 0 1 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 1 1
 0 1 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 1 0 0 1 0 0 0 0 0 1 0 1 1 1
 0 1 0 1 1 1 0 0 1 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 1 0 1 0 1 0 0 0 0 0 1
 1 1 0 1 1 1 1 1 0 0 1 1 0 0 0 1 0 0 0 0 1 1 1 0 1 0 0 1 1 0 0 1 1 1 1 1 0
 0 1 0 0 1 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0
 1 1 1 1 0 1 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 1 0 0 0 0 1 1 1 1 0 1 0 1 0 1 1
 0 0 0 1 1 1 1 1 0 1 0 1 0 0 1 1 0 0 1 0 0 0 1 0 1 0 0 1 1 0 0 0 1 1 1 0 1
 0 0 1 0 0 1 1 1 1 0 0 1 0 0 1 1 0 1 1 1 0 1 1 1 0 1 0 0 1 1 0 1 0 1 0 1 1
 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 1 1 0 1 0 1 1 0 1 1
 1 1 0 0 1 0 1 0 0 0 1 1 

In [8]:
print(X_test)

[[-1.28357596e+01  6.57461543e+00 -1.27884625e+01 ... -8.17680256e-01
  -5.21029796e-01  3.73200000e+01]
 [ 1.01542485e-01  8.43042295e-01 -2.41025491e-01 ...  2.47188450e-01
   7.49975910e-02  2.58000000e+00]
 [ 3.04267750e-01  7.78306345e-01 -1.22626150e+00 ... -7.63815960e-02
  -1.25007990e-02  1.37520000e+02]
 ...
 [-3.05523800e+01  1.67133892e+01 -3.11036848e+01 ...  1.23263630e+00
   3.56660011e-01  9.99900000e+01]
 [ 5.46821520e-02  1.85649960e+00 -4.07545074e+00 ...  4.31182443e-01
   1.10698252e-01  8.09000000e+01]
 [-1.54878810e+00  1.80869795e+00 -9.53509034e-01 ...  6.25922215e-01
   3.95573378e-01  7.69400000e+01]]


In [9]:
print(y_test)

[1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 1 0 0 1 0 1 1 0 0 1 1 1 1 0 0 1 0 1 1 0
 1 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 1 1 0 1 0 1 1 0 1 1 1 1 1 0 1 1 0
 0 0 0 1 0 1 1 0 0 1 0 1 1 0 0 1 0 0 1 0 0 0 1 0 0 1 1 1 1 0 0 0 0 1 0 1 1
 1 0 1 0 1 1 0 0 1 1 1 1 1 1 1 0 1 1 1 0 1 1 0 0 0 0 0 1 1 1 1 1 0 1 1 1 0
 1 0 1 0 1 0 1 1 1 1 0 1 1 0 1 1 0 1 0 1 1 1 0 0 1 0 0 0 1 0 0 1 0 1 1 1 0
 1 0 1 0 1 1 1 0 0 0 0 1 0 1 0 1 0 1 0 0 1 1 1]


## Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
print(X_train)

[[-0.16844443  0.21828392  0.0663109  ... -0.36572281 -1.78044673
  -0.14170911]
 [ 0.26594229 -0.52357771  0.96736808 ...  0.22877784  0.31902446
  -0.37419486]
 [-0.24403994  0.34498226  0.64056695 ... -0.07381361  0.02452478
  -0.4241738 ]
 ...
 [ 0.21804584  0.42454429 -0.42443874 ...  0.15652814  0.41661061
  -0.345451  ]
 [ 0.08897567  0.83373992 -0.37611984 ...  0.80027885  1.24716653
  -0.42675644]
 [-0.41519138  0.39794025 -0.15115683 ...  0.12427279  0.26068413
  -0.42675644]]


In [12]:
print(X_test)

[[-1.92956681  1.29527015 -1.51618988 ... -0.8563541  -1.26403332
  -0.25304975]
 [ 0.43963648 -0.30139244  0.56837195 ...  0.17380722  0.1084357
  -0.41919982]
 [ 0.47676148 -0.31942614  0.40469029 ... -0.13921668 -0.09304637
   0.22617413]
 ...
 [-5.17400489  4.11966067 -4.55897969 ...  1.12713625  0.75701822
   0.04668039]
 [ 0.43105497 -0.01907041 -0.06865826 ...  0.35180427  0.19064341
  -0.04462084]
 [ 0.13741206 -0.03238666  0.45000388 ...  0.54019687  0.84662382
  -0.06356023]]


## Training the Logistic Regression model on the Training set

In [13]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

## Predicting the Test set results

In [14]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]

## Bias and Variance

In [15]:
from mlxtend.evaluate import bias_variance_decomp
from sklearn import metrics
mse, bias, var = bias_variance_decomp(classifier, X_train, y_train, X_test, y_test, loss='0-1_loss', num_rounds=100, random_seed=0)
print('MSE from bias_variance lib [avg expected loss]: %.3f' % mse)
print('Avg Bias: %.3f' % bias)
print('Avg Variance: %.3f' % var)
print('Mean Square error by Sckit-learn lib: %.3f' % metrics.mean_squared_error(y_test,y_pred))

MSE from bias_variance lib [avg expected loss]: 0.037
Avg Bias: 0.034
Avg Variance: 0.016
Mean Square error by Sckit-learn lib: 0.029


## Making the Confusion Matrix

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred)*100)

[[ 97   2]
 [  4 105]]
97.11538461538461


In [17]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 7)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 93.96 %
Standard Deviation: 1.78 %
